name: Daily Run Script

on:
  schedule:
    # Esse cron executa às 17:00 UTC diariamente.
    - cron: "0 20 * * *"
  workflow_dispatch:  # Permite a execução manual, se necessário

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Faz o checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Passo 2: Configura o Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Passo 3: Instala as dependências
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        # Caso não tenha o requirements.txt, você pode usar:
        # pip install requests google-api-python-client google-auth google-auth-httplib2 google-auth-oauthlib

      # Passo 4: Cria o arquivo de credenciais da conta de serviço
      - name: Set up service account credentials
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: echo "$GCP_SERVICE_ACCOUNT_JSON" > service-account.json

      # Passo 5: Executa o script
      - name: Run Script
        run: python main.py
